version: "3"
services:
  app:
    build: .
    command: python serve.py -log_file_prefix=logs/server.log
    environment:
      - REDIS_HOST=redis
      - REDIS_PWD=
      - REDIS_PORT=6379
      - REDIS_CHANNEL=0
    ports:
      - 50001-50005:8888

    volumes:
      - .:/home
      - ./logs:/home/logs
      - ./data_file/cet_file:/home/data_file/cet_file
    depends_on:
      - redis
    links:
      - redis
    network_mode: bridge

  lb:
    image: dockercloud/haproxy  #负载均衡的镜像
    links:      #连接到上面的service名为web的App
      - app
    ports:
      - 50000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    network_mode: bridge

  redis:
    image: redis:alpine
    network_mode: bridge

