version: "3"
services:
  app:
    container_name: cet_server
    build: .
    command: python serve.py -log_file_prefix=logs/server.log
    environment:
      - REDIS_HOST=redis
    ports:
      - "8888:8888"
    volumes:
      - .:/home
      - ./logs:/home/logs
      - ./data_file/cet_file:/home/data_file/cet_file
    depends_on:
      - redis
      
  redis:
    image: redis:alpine
